version: '2.2'
services: 
    mongodb :
        image: mongo:latest
        restart: always
        volumes: 
            - /Users/techmaster/Documents/data:/data/db
    
    nodejs :
        image: demo-service:latest
        depends_on: 
            - mongodb
        ports: 
            - "8080:3000"
        restart: always
        environment: 
            MONGODB_URI : mongodb://mongodb:27017/demo
            PORT : 3000